INSERT INTO BuyRequests (NumShares, Symbol, MaxPrice, AccountID) VALUES ('100', 'IBM','45', 'Hokie123')
INSERT INTO BuyRequests (NumShares, Symbol, MaxPrice, AccountID) VALUES ('50', 'GOOGL','60', 'Hokie123')
INSERT INTO BuyRequests (NumShares, Symbol, MaxPrice, AccountID) VALUES ('120', 'AMZN','70', 'Hokie123')
INSERT INTO SellRequests (NumShares, Symbol, MinPrice, AccountID) VALUES ('30', 'ORCL','25', 'Hokie123')
INSERT INTO SellRequests (NumShares, Symbol, MinPrice, AccountID) VALUES ('20', 'GOOGL','40', 'Hokie123')